groups:
  items:
    - type: SEQUENCE_GROUP
      title: GemIntialize
      description: 联机初始化
    - type: SEQUENCE_GROUP
      title: ControlStatusChange
      description: 控制状态变更
    - type: SEQUENCE_GROUP
      title: ProcessStateChange
      description: 作业状态变更
    - type: SEQUENCE_GROUP
      title: LotStartAndEnd
      description: 作业批次开始和结束
    - type: SEQUENCE_GROUP
      title: RecipeParameterChange
      description: 当前程序参数或程序变更
    - type: SEQUENCE_GROUP
      title: RecipeDownAndLoad
      description: 程序下载和加载
    - type: SEQUENCE_GROUP
      title: RecipeUploadFromHostReq
      description: 请求设备上传程序
    - type: SEQUENCE_GROUP
      title: RecipeDownloadToEquipment
      description: 传输程序到设备
    - type: SEQUENCE_GROUP
      title: RecipeUploadToServer
      description: 读取设备程序到服务器
    - type: SEQUENCE_GROUP
      title: EquipmentStatus
      description: 设备状态系列
    - type: SEQUENCE_GROUP
      title: TerminalRemoteCommand
      description: 设备远程指令系列
    - type: SEQUENCE_GROUP
      title: ExceptionReporting
      description: 异常或警告系列
    - type: SEQUENCE_GROUP
      title: DataCollection
      description: 数据收集系列
    - type: SEQUENCE_GROUP
      title: ProcessProgramManagement
      description: 设备程序管理系列
    - type: SEQUENCE_GROUP
      title: SystemErrors
      description: 设备报错系列
    - type: SEQUENCE_GROUP
      title: TerminalServices
      description: 设备终端服务系列
    - type: SEQUENCE_GROUP
      title: AbortTransaction
      description: 设备指令取消系列

